import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

interface FileSpec {
  path: string;
  content: string;
}

const FILES: FileSpec[] = [
  {
    path: "lw-project.yaml",
    content: `name: my-comms
version: 1
validation:
  profile: strict
dataSources:
  - name: DATA
    schema: schemas/DATA.schema.json
theme:
  tokens:
    color-brand: "#4f46e5"
`,
  },
  {
    path: "schemas/DATA.schema.json",
    content: `${JSON.stringify(
      {
        $schema: "https://json-schema.org/draft/2020-12/schema",
        title: "DATA",
        type: "object",
        required: ["customer"],
        properties: {
          locale: { type: "string", default: "en-US" },
          customer: {
            type: "object",
            required: ["name"],
            properties: {
              name: { type: "string" },
              type: { type: "string", enum: ["B2B", "B2C"] },
            },
          },
          items: {
            type: "array",
            items: {
              type: "object",
              properties: { label: { type: "string" }, amount: { type: "number" } },
            },
          },
        },
      },
      null,
      2,
    )}\n`,
  },
  {
    path: "fixtures/sample.json",
    content: `${JSON.stringify(
      {
        DATA: {
          locale: "en-US",
          customer: { name: "Example Corp", type: "B2B" },
          items: [
            { label: "Service A", amount: 100 },
            { label: "Service B", amount: 250.5 },
          ],
        },
      },
      null,
      2,
    )}\n`,
  },
  {
    path: "templates/letter.lw",
    content: `<template id="letter" version="1.0.0" data-sources="DATA" title="Welcome letter">
  <h1>Welcome, {{ DATA.customer.name }}</h1>

  <section if="DATA.customer.type == 'B2B'">
    <p class="muted">Business account summary</p>
  </section>

  <table if="DATA.items.length > 0">
    <thead><tr><th>Item</th><th class="amount">Amount</th></tr></thead>
    <tbody>
      <tr repeat="row in DATA.items">
        <td>{{ row.label }}</td>
        <td class="amount" data-bind="row.amount" format="currency" currency="USD"></td>
      </tr>
    </tbody>
  </table>

  <footer ai-editable="false" class="muted">
    <p>Generated by lw-text. This content is locked from AI edits.</p>
  </footer>
</template>
`,
  },
  {
    path: "AGENTS.md",
    content: `# AGENTS.md

This repository contains **lw-text** document templates.

1. Primary datasource: \`DATA\` — bindings must exist in \`schemas/DATA.schema.json\`.
2. Author \`.lw\` templates in \`templates/\`; reusable blocks in \`blocks/\`.
3. Never edit nodes marked \`ai-editable="false"\`.
4. Add/update a fixture in \`fixtures/\` for any new bindings.
5. Run \`lw validate\` before finishing.
`,
  },
];

export function createProject(dir: string): string[] {
  const created: string[] = [];
  for (const f of FILES) {
    const full = join(dir, f.path);
    if (existsSync(full)) continue;
    mkdirSync(join(full, ".."), { recursive: true });
    writeFileSync(full, f.content, "utf8");
    created.push(f.path);
  }
  return created;
}
